version: '3'
services:
  worker:
    build: .
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017/mapdb?authSource=admin
      - MONGO_USERNAME=docker
      - MONGO_PASSWORD=docker
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo/data:/mongo/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker
    ports:
      - '27017:27017'
